import flyerMusic from "@/assets/flyer-music.jpg";
import flyerSports from "@/assets/flyer-sports.jpg";
import flyerBusiness from "@/assets/flyer-business.jpg";
import flyerCulture from "@/assets/flyer-culture.jpg";
import flyerNightlife from "@/assets/flyer-nightlife.jpg";
import flyerCommunity from "@/assets/flyer-community.jpg";
import type { EventRecord, Organizer } from "./types";

const day = (offset: number) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
};

const history = (base: number, spread: number) =>
  Array.from({ length: 7 }, (_, i) => ({
    date: day(i - 6),
    pinClicks: Math.round(base + Math.sin(i) * spread + i * 2),
    directionClicks: Math.round(base / 4 + Math.cos(i) * (spread / 3) + i),
  }));

export const seedOrganizers: Organizer[] = [
  {
    id: "org-1",
    name: "Mount Fako Collective",
    email: "planner@bubverse.app",
    password: "planner123",
    bio: "Culture and music programming across Buea.",
    channels: [
      { type: "WhatsApp", value: "+237 6 77 00 11 22" },
      { type: "Instagram", value: "https://instagram.com/mountfako" },
    ],
    showContactsPublicly: false,
    status: "Verified",
    createdAt: day(-90),
  },
  {
    id: "org-2",
    name: "Douala Nights Agency",
    email: "nights@bubverse.app",
    password: "planner123",
    bio: "Nightlife and lifestyle events in Douala.",
    channels: [{ type: "Mobile phone", value: "+237 6 99 44 33 21" }],
    showContactsPublicly: true,
    status: "Pending Verification",
    createdAt: day(-20),
  },
  {
    id: "org-3",
    name: "Southwest Sports Union",
    email: "sports@bubverse.app",
    password: "planner123",
    channels: [{ type: "Email", value: "contact@swsu.cm" }],
    showContactsPublicly: false,
    status: "Needs More Information",
    createdAt: day(-40),
  },
];

export const seedEvents: EventRecord[] = [
  {
    id: "evt-1",
    title: "Afrobeats Night Live",
    image: flyerMusic,
    description:
      "A live Afrobeats showcase with six regional acts, a full band set and an open dance floor until late.",
    category: "Music",
    date: day(3),
    startTime: "20:00",
    endTime: "23:59",
    venueName: "Molyko Open Arena",
    address: "Molyko Street, Buea, Southwest Region",
    lat: 4.1568,
    lng: 9.2871,
    organizerId: "org-1",
    pinClicks: 184,
    directionClicks: 42,
    status: "Published",
    createdAt: day(-14),
    updatedAt: day(-2),
    history: history(20, 6),
  },
  {
    id: "evt-2",
    title: "Buea Community Football Cup",
    image: flyerSports,
    description:
      "Sixteen neighbourhood teams compete across a single day of knockout matches. Free entry for spectators.",
    category: "Sports",
    date: day(6),
    startTime: "09:00",
    endTime: "17:00",
    venueName: "Buea Town Stadium",
    address: "Buea Town, Southwest Region",
    lat: 4.1489,
    lng: 9.2405,
    organizerId: "org-3",
    pinClicks: 96,
    directionClicks: 31,
    status: "Published",
    createdAt: day(-10),
    updatedAt: day(-3),
    history: history(12, 4),
  },
  {
    id: "evt-3",
    title: "Startup Business Summit",
    image: flyerBusiness,
    description:
      "Founders, investors and operators meet for a day of talks on building companies in Cameroon.",
    category: "Business",
    date: day(12),
    startTime: "08:30",
    endTime: "16:00",
    venueName: "Mountain Hotel Conference Hall",
    address: "Mountain Hotel, Buea, Southwest Region",
    lat: 4.1621,
    lng: 9.2464,
    organizerId: "org-1",
    pinClicks: 143,
    directionClicks: 55,
    status: "Published",
    createdAt: day(-21),
    updatedAt: day(-5),
    history: history(16, 5),
  },
  {
    id: "evt-4",
    title: "Cultural Heritage Festival",
    image: flyerCulture,
    description:
      "Traditional dance troupes, craft stalls and a heritage food market spread across the palace grounds.",
    category: "Culture",
    date: day(9),
    startTime: "11:00",
    endTime: "20:00",
    venueName: "Bonanjo Cultural Grounds",
    address: "Bonanjo, Douala, Littoral Region",
    lat: 4.0433,
    lng: 9.6929,
    organizerId: "org-1",
    pinClicks: 221,
    directionClicks: 78,
    status: "Published",
    createdAt: day(-30),
    updatedAt: day(-4),
    history: history(28, 8),
  },
  {
    id: "evt-5",
    title: "Rooftop Party: Neon Skyline",
    image: flyerNightlife,
    description:
      "Late-night rooftop session with resident DJs, a skyline view over Akwa and a strict 21+ door policy.",
    category: "Nightlife",
    date: day(2),
    startTime: "22:00",
    endTime: "04:00",
    venueName: "Skyline Terrace Akwa",
    address: "Rue Joss, Akwa, Douala",
    lat: 4.0511,
    lng: 9.7085,
    organizerId: "org-2",
    pinClicks: 310,
    directionClicks: 121,
    status: "Published",
    createdAt: day(-8),
    updatedAt: day(-1),
    history: history(40, 12),
  },
  {
    id: "evt-6",
    title: "Neighbourhood Cleanup Day",
    image: flyerCommunity,
    description:
      "Volunteer cleanup along the Bonapriso corridor. Gloves, bags and refreshments provided on site.",
    category: "Community",
    date: day(5),
    startTime: "07:00",
    endTime: "12:00",
    venueName: "Bonapriso Market Square",
    address: "Bonapriso, Douala, Littoral Region",
    lat: 4.0301,
    lng: 9.7145,
    organizerId: "org-2",
    pinClicks: 58,
    directionClicks: 19,
    status: "Published",
    createdAt: day(-6),
    updatedAt: day(-1),
    history: history(8, 3),
  },
  {
    id: "evt-7",
    title: "Sunset Acoustic Session",
    image: flyerMusic,
    description:
      "An intimate acoustic set from three songwriters, seated capacity of 120 on the garden lawn.",
    category: "Music",
    date: day(15),
    startTime: "17:30",
    endTime: "21:00",
    venueName: "Great Soppo Gardens",
    address: "Great Soppo, Buea, Southwest Region",
    lat: 4.1454,
    lng: 9.2612,
    organizerId: "org-1",
    pinClicks: 47,
    directionClicks: 12,
    status: "Unpublished",
    createdAt: day(-4),
    updatedAt: day(-1),
    history: history(6, 2),
  },
  {
    id: "evt-8",
    title: "Akwa Street Food Carnival",
    image: flyerCulture,
    description:
      "Forty vendors line the boulevard for a weekend of regional street food and live percussion.",
    category: "Culture",
    date: day(20),
    startTime: "12:00",
    endTime: "22:00",
    venueName: "Boulevard de la Liberté",
    address: "Akwa, Douala, Littoral Region",
    lat: 4.0562,
    lng: 9.7012,
    organizerId: "org-2",
    pinClicks: 132,
    directionClicks: 44,
    status: "Published",
    createdAt: day(-12),
    updatedAt: day(-2),
    history: history(18, 6),
  },
];

export const ADMIN_CREDENTIALS = { email: "admin@bubverse.app", password: "admin123" };
